plugins {
    id "com.github.node-gradle.node" version "5.0.0"
}

node {
    download.set(true)
    version.set("18.17.1")
    npmVersion.set("9.6.7")
}

task build

task customNpmInstall(type: NpmTask) {
    args = ['install']
}

task customNpmTest(type: NpmTask) {
    args = ['test']
}

task customNpmBuild(type: NpmTask) {
    args = ['run', 'build']
}

task zip(type: Zip) {
    from('.') {
        include "*"
        include "bin/**"
        include "data/**"
        include "node_modules/**"
        include "public/**"
        include "routes/**"
        include "views/**"
    }
    destinationDir(file("dist"))
    archiveBaseName.set("trainSchedule")
}

build.dependsOn zip
zip.dependsOn customNpmBuild
customNpmBuild.dependsOn customNpmTest
customNpmTest.dependsOn customNpmInstall

